//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachments", Namespace="http://tempuri.org/")]
    public partial class Attachments : object
    {
        
        private string AttachmentNameField;
        
        private byte[] attachmentField;
        
        private string extensionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AttachmentName
        {
            get
            {
                return this.AttachmentNameField;
            }
            set
            {
                this.AttachmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] attachment
        {
            get
            {
                return this.attachmentField;
            }
            set
            {
                this.attachmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailService.MailTransportSoap")]
    public interface MailTransportSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.SendEmailResponse> SendEmailAsync(EmailService.SendEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailTest", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.SendEmailTestResponse> SendEmailTestAsync(EmailService.SendEmailTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailAlternateView", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.sendEmailAlternateViewResponse> sendEmailAlternateViewAsync(EmailService.sendEmailAlternateViewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.sendEmailAppointmentResponse> sendEmailAppointmentAsync(EmailService.sendEmailAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailWithAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.sendEmailWithAttachmentResponse> sendEmailWithAttachmentAsync(EmailService.sendEmailWithAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendEmailWithAttachmentList", ReplyAction="*")]
        System.Threading.Tasks.Task<EmailService.sendEmailWithAttachmentListResponse> sendEmailWithAttachmentListAsync(EmailService.sendEmailWithAttachmentListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmail", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.SendEmailRequestBody Body;
        
        public SendEmailRequest()
        {
        }
        
        public SendEmailRequest(EmailService.SendEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string body;
        
        public SendEmailRequestBody()
        {
        }
        
        public SendEmailRequestBody(string from, string to, string subject, string body)
        {
            this.from = from;
            this.to = to;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.SendEmailResponseBody Body;
        
        public SendEmailResponse()
        {
        }
        
        public SendEmailResponse(EmailService.SendEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendEmailResponseBody
    {
        
        public SendEmailResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailTest", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.SendEmailTestRequestBody Body;
        
        public SendEmailTestRequest()
        {
        }
        
        public SendEmailTestRequest(EmailService.SendEmailTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string body;
        
        public SendEmailTestRequestBody()
        {
        }
        
        public SendEmailTestRequestBody(string from, string to, string subject, string body)
        {
            this.from = from;
            this.to = to;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailTestResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.SendEmailTestResponseBody Body;
        
        public SendEmailTestResponse()
        {
        }
        
        public SendEmailTestResponse(EmailService.SendEmailTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendEmailTestResult;
        
        public SendEmailTestResponseBody()
        {
        }
        
        public SendEmailTestResponseBody(string SendEmailTestResult)
        {
            this.SendEmailTestResult = SendEmailTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailAlternateViewRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailAlternateView", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailAlternateViewRequestBody Body;
        
        public sendEmailAlternateViewRequest()
        {
        }
        
        public sendEmailAlternateViewRequest(EmailService.sendEmailAlternateViewRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailAlternateViewRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Image;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContentId;
        
        public sendEmailAlternateViewRequestBody()
        {
        }
        
        public sendEmailAlternateViewRequestBody(string from_Email, string to_Email, string body, string Subject, string Image, string ContentId)
        {
            this.from_Email = from_Email;
            this.to_Email = to_Email;
            this.body = body;
            this.Subject = Subject;
            this.Image = Image;
            this.ContentId = ContentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailAlternateViewResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailAlternateViewResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailAlternateViewResponseBody Body;
        
        public sendEmailAlternateViewResponse()
        {
        }
        
        public sendEmailAlternateViewResponse(EmailService.sendEmailAlternateViewResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sendEmailAlternateViewResponseBody
    {
        
        public sendEmailAlternateViewResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailAppointmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailAppointment", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailAppointmentRequestBody Body;
        
        public sendEmailAppointmentRequest()
        {
        }
        
        public sendEmailAppointmentRequest(EmailService.sendEmailAppointmentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailAppointmentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string method;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string appointmentInfo;
        
        public sendEmailAppointmentRequestBody()
        {
        }
        
        public sendEmailAppointmentRequestBody(string from_Email, string to_Email, string method, string appointmentInfo)
        {
            this.from_Email = from_Email;
            this.to_Email = to_Email;
            this.method = method;
            this.appointmentInfo = appointmentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailAppointmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailAppointmentResponseBody Body;
        
        public sendEmailAppointmentResponse()
        {
        }
        
        public sendEmailAppointmentResponse(EmailService.sendEmailAppointmentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sendEmailAppointmentResponseBody
    {
        
        public sendEmailAppointmentResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailWithAttachmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailWithAttachment", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailWithAttachmentRequestBody Body;
        
        public sendEmailWithAttachmentRequest()
        {
        }
        
        public sendEmailWithAttachmentRequest(EmailService.sendEmailWithAttachmentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailWithAttachmentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] attachment;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AttachmentName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string extension;
        
        public sendEmailWithAttachmentRequestBody()
        {
        }
        
        public sendEmailWithAttachmentRequestBody(string from_Email, string to_Email, string body, string Subject, byte[] attachment, string AttachmentName, string extension)
        {
            this.from_Email = from_Email;
            this.to_Email = to_Email;
            this.body = body;
            this.Subject = Subject;
            this.attachment = attachment;
            this.AttachmentName = AttachmentName;
            this.extension = extension;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailWithAttachmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailWithAttachmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailWithAttachmentResponseBody Body;
        
        public sendEmailWithAttachmentResponse()
        {
        }
        
        public sendEmailWithAttachmentResponse(EmailService.sendEmailWithAttachmentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sendEmailWithAttachmentResponseBody
    {
        
        public sendEmailWithAttachmentResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailWithAttachmentListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailWithAttachmentList", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailWithAttachmentListRequestBody Body;
        
        public sendEmailWithAttachmentListRequest()
        {
        }
        
        public sendEmailWithAttachmentListRequest(EmailService.sendEmailWithAttachmentListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendEmailWithAttachmentListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public EmailService.ArrayOfString to_Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EmailService.Attachments[] attachments;
        
        public sendEmailWithAttachmentListRequestBody()
        {
        }
        
        public sendEmailWithAttachmentListRequestBody(string from_Email, EmailService.ArrayOfString to_Email, string body, string Subject, EmailService.Attachments[] attachments)
        {
            this.from_Email = from_Email;
            this.to_Email = to_Email;
            this.body = body;
            this.Subject = Subject;
            this.attachments = attachments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendEmailWithAttachmentListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendEmailWithAttachmentListResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmailService.sendEmailWithAttachmentListResponseBody Body;
        
        public sendEmailWithAttachmentListResponse()
        {
        }
        
        public sendEmailWithAttachmentListResponse(EmailService.sendEmailWithAttachmentListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sendEmailWithAttachmentListResponseBody
    {
        
        public sendEmailWithAttachmentListResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MailTransportSoapChannel : EmailService.MailTransportSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MailTransportSoapClient : System.ServiceModel.ClientBase<EmailService.MailTransportSoap>, EmailService.MailTransportSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MailTransportSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MailTransportSoapClient.GetBindingForEndpoint(endpointConfiguration), MailTransportSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailTransportSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MailTransportSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailTransportSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MailTransportSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MailTransportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.SendEmailResponse> EmailService.MailTransportSoap.SendEmailAsync(EmailService.SendEmailRequest request)
        {
            return base.Channel.SendEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.SendEmailResponse> SendEmailAsync(string from, string to, string subject, string body)
        {
            EmailService.SendEmailRequest inValue = new EmailService.SendEmailRequest();
            inValue.Body = new EmailService.SendEmailRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((EmailService.MailTransportSoap)(this)).SendEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.SendEmailTestResponse> EmailService.MailTransportSoap.SendEmailTestAsync(EmailService.SendEmailTestRequest request)
        {
            return base.Channel.SendEmailTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.SendEmailTestResponse> SendEmailTestAsync(string from, string to, string subject, string body)
        {
            EmailService.SendEmailTestRequest inValue = new EmailService.SendEmailTestRequest();
            inValue.Body = new EmailService.SendEmailTestRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            return ((EmailService.MailTransportSoap)(this)).SendEmailTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.sendEmailAlternateViewResponse> EmailService.MailTransportSoap.sendEmailAlternateViewAsync(EmailService.sendEmailAlternateViewRequest request)
        {
            return base.Channel.sendEmailAlternateViewAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.sendEmailAlternateViewResponse> sendEmailAlternateViewAsync(string from_Email, string to_Email, string body, string Subject, string Image, string ContentId)
        {
            EmailService.sendEmailAlternateViewRequest inValue = new EmailService.sendEmailAlternateViewRequest();
            inValue.Body = new EmailService.sendEmailAlternateViewRequestBody();
            inValue.Body.from_Email = from_Email;
            inValue.Body.to_Email = to_Email;
            inValue.Body.body = body;
            inValue.Body.Subject = Subject;
            inValue.Body.Image = Image;
            inValue.Body.ContentId = ContentId;
            return ((EmailService.MailTransportSoap)(this)).sendEmailAlternateViewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.sendEmailAppointmentResponse> EmailService.MailTransportSoap.sendEmailAppointmentAsync(EmailService.sendEmailAppointmentRequest request)
        {
            return base.Channel.sendEmailAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.sendEmailAppointmentResponse> sendEmailAppointmentAsync(string from_Email, string to_Email, string method, string appointmentInfo)
        {
            EmailService.sendEmailAppointmentRequest inValue = new EmailService.sendEmailAppointmentRequest();
            inValue.Body = new EmailService.sendEmailAppointmentRequestBody();
            inValue.Body.from_Email = from_Email;
            inValue.Body.to_Email = to_Email;
            inValue.Body.method = method;
            inValue.Body.appointmentInfo = appointmentInfo;
            return ((EmailService.MailTransportSoap)(this)).sendEmailAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.sendEmailWithAttachmentResponse> EmailService.MailTransportSoap.sendEmailWithAttachmentAsync(EmailService.sendEmailWithAttachmentRequest request)
        {
            return base.Channel.sendEmailWithAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.sendEmailWithAttachmentResponse> sendEmailWithAttachmentAsync(string from_Email, string to_Email, string body, string Subject, byte[] attachment, string AttachmentName, string extension)
        {
            EmailService.sendEmailWithAttachmentRequest inValue = new EmailService.sendEmailWithAttachmentRequest();
            inValue.Body = new EmailService.sendEmailWithAttachmentRequestBody();
            inValue.Body.from_Email = from_Email;
            inValue.Body.to_Email = to_Email;
            inValue.Body.body = body;
            inValue.Body.Subject = Subject;
            inValue.Body.attachment = attachment;
            inValue.Body.AttachmentName = AttachmentName;
            inValue.Body.extension = extension;
            return ((EmailService.MailTransportSoap)(this)).sendEmailWithAttachmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailService.sendEmailWithAttachmentListResponse> EmailService.MailTransportSoap.sendEmailWithAttachmentListAsync(EmailService.sendEmailWithAttachmentListRequest request)
        {
            return base.Channel.sendEmailWithAttachmentListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailService.sendEmailWithAttachmentListResponse> sendEmailWithAttachmentListAsync(string from_Email, EmailService.ArrayOfString to_Email, string body, string Subject, EmailService.Attachments[] attachments)
        {
            EmailService.sendEmailWithAttachmentListRequest inValue = new EmailService.sendEmailWithAttachmentListRequest();
            inValue.Body = new EmailService.sendEmailWithAttachmentListRequestBody();
            inValue.Body.from_Email = from_Email;
            inValue.Body.to_Email = to_Email;
            inValue.Body.body = body;
            inValue.Body.Subject = Subject;
            inValue.Body.attachments = attachments;
            return ((EmailService.MailTransportSoap)(this)).sendEmailWithAttachmentListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MailTransportSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MailTransportSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MailTransportSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.uj.ac.za/test/UJEmailService/MailTransport.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MailTransportSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.uj.ac.za/test/UJEmailService/MailTransport.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MailTransportSoap,
            
            MailTransportSoap12,
        }
    }
}
