// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UCDG.Persistence;

namespace UCDG.Persistence.Migrations
{
    [DbContext(typeof(UCDGDbContext))]
    [Migration("20210331065151_fixCommets_column")]
    partial class fixCommets_column
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UCDG.Domain.Entities.ApplicationStatus", b =>
                {
                    b.Property<int>("ApplicationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationStatusId");

                    b.ToTable("ApplicationStatus");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Applications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicantCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantProgress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApplicationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ApplicationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApplicationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentDescribe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppointmentOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CareerFinancialSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CareerTeachingRelief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DHETFundsRequested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepartmentContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Describe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FacultyContibution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FinancialMotivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstYearRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FundingCallsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FundingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FundingStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSavedStep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlannedGraduationYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ResearchFundsContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudyingTowards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationStatusId");

                    b.HasIndex("FundingCallsId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.ApplicationsProjects", b =>
                {
                    b.Property<int>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ApplicationsProjects");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationsId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentExtention")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DocumentFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationsId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.EmailsSent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationsId");

                    b.ToTable("EmailsSent");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.FundingCallStatus", b =>
                {
                    b.Property<int>("FundingCallStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundingCallStatusId");

                    b.ToTable("FundingCallStatus");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.FundingCalls", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FundingCallName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FundingCallStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FundingCallStatusId");

                    b.ToTable("FundingCalls");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.FundingCallsProjects", b =>
                {
                    b.Property<int>("FundingCallsId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("int");

                    b.HasKey("FundingCallsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("FundingCallsProjects");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Payments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<double>("MonthTotal")
                        .HasColumnType("float");

                    b.Property<int>("NumberOfWeeks")
                        .HasColumnType("int");

                    b.Property<double>("RatePerHour")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Step")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalNumberOfHours")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationsId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.PersistentSettings", b =>
                {
                    b.Property<int>("PersistentSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersistentSettingsKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersistentSettingsValue")
                        .HasColumnType("int");

                    b.HasKey("PersistentSettingsId");

                    b.ToTable("PersistentSettings");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.ProjectCycles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectCycles");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ProjectCyclesId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCyclesId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualificationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QualificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.TemporaryAppointees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationsId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationsId");

                    b.ToTable("TemporaryAppointees");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlternativeEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Campus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HODStaffNUmber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPassportNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAcademic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OtherFundSource")
                        .HasColumnType("bit");

                    b.Property<string>("OtherFundSourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OtherProgramme")
                        .HasColumnType("bit");

                    b.Property<string>("OtherProgrammeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViceDean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViceDeanStaffNUmber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Applications", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.ApplicationStatus", "ApplicationStatus")
                        .WithMany()
                        .HasForeignKey("ApplicationStatusId");

                    b.HasOne("UCDG.Domain.Entities.FundingCalls", "FundingCalls")
                        .WithMany()
                        .HasForeignKey("FundingCallsId");

                    b.HasOne("UCDG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.ApplicationsProjects", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Applications", "Applications")
                        .WithMany()
                        .HasForeignKey("ApplicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCDG.Domain.Entities.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Comments", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Applications", "Applications")
                        .WithMany()
                        .HasForeignKey("ApplicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCDG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Documents", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Applications", "Applications")
                        .WithMany()
                        .HasForeignKey("ApplicationsId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.EmailsSent", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Applications", "Applications")
                        .WithMany()
                        .HasForeignKey("ApplicationsId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.FundingCalls", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.FundingCallStatus", "FundingCallStatus")
                        .WithMany()
                        .HasForeignKey("FundingCallStatusId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.FundingCallsProjects", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.FundingCalls", "FundingCalls")
                        .WithMany()
                        .HasForeignKey("FundingCallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCDG.Domain.Entities.Projects", "Projects")
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Payments", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Applications", "Applications")
                        .WithMany()
                        .HasForeignKey("ApplicationsId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Projects", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.ProjectCycles", "ProjectCycles")
                        .WithMany()
                        .HasForeignKey("ProjectCyclesId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.Qualification", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.User", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UCDG.Domain.Entities.TemporaryAppointees", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Applications", "Applications")
                        .WithMany()
                        .HasForeignKey("ApplicationsId");
                });

            modelBuilder.Entity("UCDG.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("UCDG.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UCDG.Domain.Entities.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
